[workspace]
resolver = "2"
members = ["v_plugin", "yadi"]

[package]
name = "v"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { version = "1" }
tokio = { version = "1", features = ["full"] }
v_plugin = { path = "v_plugin" }
yadi = { path = "yadi" }
