[package]
name = "ddd-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = { version = "0.20" }
ddd = { path = "../ddd" }
quote = { version = "1" }
syn = { version = "2" }